// <auto-generated />
using EmployeeDepartmentApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeDepartmentApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("EmployeeDepartmentApp.API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<string>("DateTimeCreated");

                    b.Property<int>("DateTimeUpdated");

                    b.Property<int>("LastTimeUpdated");

                    b.Property<string>("Name");

                    b.Property<string>("Updatedby");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EmployeeDepartmentApp.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<string>("DateOfBirth");

                    b.Property<string>("DateTimeCreated");

                    b.Property<int>("DateTimeUpdated");

                    b.Property<string>("Firstname");

                    b.Property<int>("LastTimeUpdated");

                    b.Property<string>("Lastname");

                    b.Property<string>("Updatedby");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeDepartmentApp.API.Models.EmployeeDepartmentRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy");

                    b.Property<string>("DateTimeCreated");

                    b.Property<int>("DateTimeUpdated");

                    b.Property<int>("DepartmentId");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("LastTimeUpdated");

                    b.Property<string>("Updatedby");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeDepartmentRelations");
                });

            modelBuilder.Entity("EmployeeDepartmentApp.API.Models.EmployeeDepartmentRelation", b =>
                {
                    b.HasOne("EmployeeDepartmentApp.API.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmployeeDepartmentApp.API.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
